### ISSUE TITLE
Locations erstellen

### ISSUE THREAD

**Issue by Malu010** [GameDevWS2024/Corebound#45]
### **Bitte noch #49 ergänzen.** (Map)

**Bis Freitag:** Erstellung von Rätsel für die einzelnen Orte damit das Coding Team anfangen kann, die Rätsel zu implementieren. Tragt euch bitte dazu für den jeweiligen Ort ein, den ihr machen wollt und setzt ein Hacken in die Boxen, wenn ihr fertig seid. Partnerarbeit ist natürlich möglich. Überlegt euch auch wie man den Befehl "Interact" implementieren kann - also was soll interact machen? Zb. einen Objekt untersuchen, einen Schalter umlegen, etc.

- [x] Geisterhaus #43 @TamedNightFury (Eileen)
- [x] Space Port #50 @Malu010 (Luiz)
- [x] Haunted Forrest #48 @Patrick-Woelfle (unten in kommentar)
- [ ] Military Station:
- [ ] Abandonded Mine:
- [ ] #47
- [x] Giant Copper Tree #[TO BE REPLACED] @Patrick-Woelfle (unten in kommentar)
- [ ] Top of a Mountain:
- [ ] Swamp Village:

Bis Freitag muss jeder für mindestens einen Ort die Rätsel erstellt haben.

**Danach (Deadline noch unklar):**
Jeder aus dem Desgin-Team erstellt einen Ort. Dazu treffen wir uns mit @Leo-Dev-2004 und @konradbausch für notwendige Infos/Anleitung.

**Comment by Malu010** [comment]
- Ein verlassener Hafen. Es befinden sich noch einige Raumschiffe dort. Darüber hinaus gibt es ein Lager mit Ersatzteile und ein Kontrollraum
- Durchsucht werden der Lager, der Kontrollraum (in der Reihenfolge)
- Um in den Lager reinzukommen, muss der Ally ein Regal wegdrücken (interaction), der an an den Eingang von innen angelehnt ist und so den Weg versperrt.
- Mit einer weiteren Interaction "Untersuchen" schaut sich der Ally Dokumente an und entdeckt eins mit einer Warenliste die andeutet, dass man das Lager hastig geleert hat und es auf Schiffe gebracht wurde, die weggeflogen sind
- Darüber hinaus findet er einen Schlüssel für den Kontrollraum und einen abgerissen Zettel mit zwei Ziffern 
-Im Kontrollraum: Mit einer Interaction, testet der Ally die technischen Geräte aus. Sie funktionieren aber nicht mit Ausnahme vom Computer. 
Rästel: Der Ally findet aber ein Zettel auf dem draufsteht, dass die Pin für den Computer die Anzahl an Stege, gefolgt von... der Zettel bricht da ab. Der Spieler muss also entweder die letzten zwei Ziffern raten oder sich daran erinnern, dass im Lagerhaus ja ein Zettel mit zwei Ziffern gefunden wurden.
-Auf dem Computer findet der Ally dann ein Dokument, dass von den Minen spricht

**Comment by Leo-Dev-2004** [comment]
> ## Giant Copper Tree
> * Location:
>   
>   * In a clearing in the Haunted Forrest with an abandonded village of light spirits
>   * Decorated with ribbons
>   * The tree and the space around it doesn't seem as affected by the shadows as the rest of the world, because of the celebrations the spirits held there.
> * Obstacles:
>   
>   * There doesn't seem to be anything to do in the area, until the ally brings the staff to the area and interacts with the tree
>   * Then some of the roots move out of the way, revealing some reward, the easiest to implement would probably be a light orb left behind by the spirits, which makes the core stronger

Roots moving out of the way is too complex. Can it just be the tree dropping the orb that immediately upgrades the core with some sound effect?
Additionally, I think it would be a good idea to add some small puzzle like there are multiple copper trees but one stands out or you have to count in some way, etc... Be creative

**Comment by grimpoteuthis-octopoda** [comment]
Laboratory:
Location:
- Container
- Inside: laboratory, workplace, but signs of people having slept there (matress, toothbrush), empty food containers, microwave
- lab equipment: microscope, centrifuge

Obstacles:
- turn on all light sources
- obvious: lamps
- less obvious: microwave, fridge, microscope
- maybe a science-coded ally is better at this?
